# Generated by Django 5.1.7 on 2025-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='ServiceImages')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('serviename', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Phoneno', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('password', models.TextField(default='default_password', max_length=20)),
            ],
        ),
    ]
