# Generated by Django 5.1.7 on 2025-03-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproviderr',
            old_name='serviename',
            new_name='servicename',
        ),
    ]
