# Generated by Django 5.1.7 on 2025-03-21 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0002_rename_serviename_serviceproviderr_servicename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderr',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='serviceproviderr',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='serviceproviderr',
            name='username',
        ),
        migrations.AddField(
            model_name='serviceproviderr',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
