# Generated by Django 5.1.7 on 2025-03-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0003_remove_serviceproviderr_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviderr',
            name='email',
        ),
        migrations.RemoveField(
            model_name='serviceproviderr',
            name='password',
        ),
    ]
